name: grocery
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  get: ^4.6.5
  mask_text_input_formatter: ^2.4.0
  add_to_cart_animation: ^0.0.7
  badges: ^3.1.1
  intl: ^0.18.0
  dio: ^5.1.2
  json_annotation: ^4.8.1
  freezed: ^2.4.2
  fluttertoast: ^8.2.2
  flutter_secure_storage: ^8.0.0
  qr_flutter: ^4.0.0
  freezed_annotation: ^2.4.1
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  lottie: ^2.6.0

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0



flutter:
  uses-material-design: true


  assets:
    - lib/assets/fruits/apple.png
    - lib/assets/fruits/grape.png
    - lib/assets/fruits/guava.png
    - lib/assets/fruits/kiwi.png
    - lib/assets/fruits/papaya.png
    - lib/assets/fruits/mango.png
    - lib/assets/app_images/pix.png
    - lib/assets/animation.json

